### ISSUE TITLE
Compiling fails under OSX

### ISSUE THREAD

**Issue by paines** [dleslie/soil-egg#8]
In order to compile for macosx "-framework CoreFoundation" is needed in soil.setup

**Comment by dleslie** [comment]
Could you give it a shot? I think @AlexCharlton's latest pull request may have fixed it.

**Comment by paines** [comment]
> On 10 Jan 2015, at 19:58, Dan Leslie <notifications@github.com> wrote:
> 
> Could you give it a shot? I think @AlexCharlton <https://github.com/AlexCharlton>'s latest pull request may have fixed it.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dleslie/soil-egg/issues/8#issuecomment-69467361>.
> 
Hi

It compiled fine now pulled from github.

Many thanks!

Best regards
Anes=

**Comment by dleslie** [comment]
Most excellent, thank-you.
